### PR TITLE
Add api module and user endpoints

### PR DESCRIPTION
**Pull request by Haider8**
@roshnet These are the three API endpoints which you can test and review 

## For testing API endpoints:

* ### http://localhost:5000/api/v1/users [POST REQUEST]
#### Headers
`Content-Type` = `application/json`
#### Body
```
{
	"username": "haider",
	"password": "test",
	"email": "haider@test.io"
}
```
#### Response
```
{
    "_links": {
        "self": "/api/v1/users/5"
    },
    "avatar_image": null,
    "bio": null,
    "city": null,
    "first_name": null,
    "id": 5,
    "last_name": null,
    "last_seen": "Mon, 16 Sep 2019 17:12:32 GMT",
    "phone_number": null,
    "role": null,
    "state": null,
    "username": "haider"
}
```

* ### http://localhost:5000/api/v1/users/4 [GET REQUEST]
#### Response
```
{
    "_links": {
        "self": "/api/v1/users/4"
    },
    "avatar_image": null,
    "bio": "this is my new bio",
    "city": "Aligarh",
    "first_name": "Haider",
    "id": 4,
    "last_name": "Ali",
    "last_seen": "Mon, 16 Sep 2019 16:23:53 GMT",
    "phone_number": "2321321321",
    "role": "customer",
    "state": "Uttar Pradesh",
    "username": "alice"
}
```

* ### http://localhost:5000/api/v1/users/4 [PUT REQUEST]
#### Headers
`Content-Type` = `application/json`
#### Body
```
{
	"phone_number": "2321321321",
	"city": "Aligarh",
	"state": "Uttar Pradesh",
	"first_name": "Haider",
	"last_name": "Ali",
	"role": "customer"
}
```
#### Response
```
{
    "_links": {
        "self": "/api/v1/users/4"
    },
    "avatar_image": null,
    "bio": "this is my new bio",
    "city": "Aligarh",
    "first_name": "Haider",
    "id": 4,
    "last_name": "Ali",
    "last_seen": "Mon, 16 Sep 2019 16:23:53 GMT",
    "phone_number": "2321321321",
    "role": "customer",
    "state": "Uttar Pradesh",
    "username": "alice"
}
```

### CODE REVIEW

**Comment by roshnet** [comment]
Nice work @Haider8 !
However, I am facing issue regarding creation of table.
From what I get, it says - `sqlite3.OperationalError: no such table: user`

**Review by pnijhara — COMMENTED** [review]
maja aa gaya

**Comment by roshnet** [comment]
It took me a while to figure that each call to `/users` endpoint actually creates a new user.
That's why - `http://localhost:5000/api/v1/users/4` gave me a 404, as there were only 2 users created so far.
You must have documented this @Haider8 .

**Review by roshnet — APPROVED** [review]
POST  `/users/` for "haider8" :white_check_mark:
POST  `/users/` for "roshnet" :white_check_mark:
GET `/users/1` - shows info for "haider8" :white_check_mark:
GET `/users/2` - shows info for "roshnet" :white_check_mark:
PUT `/users/2` with JSON - updates values :white_check_mark:

PR is a go.

**Comment by Haider8** [comment]
My bad. See if all other things working correctly

**Pull request merged**
